language: python
python:
    - "2.7"
    - "3.4"
cache: apt
before_install:
    - sudo apt-get -qq  update -y
    - sudo apt-get install -y liblapack-dev gfortran
    - pip install codecov

install:
    - pip install -r requirements.txt

script:
    - py.test
after_success:
    - codecov
