language: python
python:
    - "2.7"
    - "3.4"
cache: apt
before_install:
    - sudo apt-get -qq  update -y
    - sudo apt-get install -y liblapack-dev gfortran
    - pip install pytest pytest-cov codecov coveralls

install:
    - pip install -r requirements.txt

script:
    - py.test --cov=.

after_success:
    - codecov
    - coveralls
